url: 'https://art.criativosonar.com'

cloudcannon:
  data: true

collections:
  art:
    icon: picture
    output: true
    permalink: /art/:title

sass:
  dir: _sass
  style: compressed  

uploads_dir: "assets/images"
css_dir: "/style"

comments:
 body_font_family: Add the font code block on the configurations menu
 heading_font_family: Add the font code block on the configuratios menu
 preview_image: Image to be shown when sharing the site on social networks
 custom_css_code_block: 'Add custom styles to your site (SCSS-compatible). This theme uses TailwindCSS 2.1. Important: You might require the assistance of a developer.'

plugins:
  - jekyll-sitemap  
  - jekyll_picture_tag
  - jekyll-postcss
  - jekyll-purgecss

picture:
  source: "/"
  output: "srcset/"
  suppress_warnings: true

channels:
  - "Facebook"
  - "Instagram"
  - "Twitter"
  - "WhatsApp"
  - "Github"
  - "Snapchat"
  - "LinkedIn"
  - "Skype"
  - "Telegram"
  - "Signal"
  - "Messenger"

artists:
  - "bruno"  
  - "gus"
  - "fer"
  - "thais"

co-artists:
  - "fellipe"
  - "alice"