general:
  site_url: 
  address:
  email:
  phone:
  social:
    - channel: "Facebook"
      add_to_chat_bubble: false
      url: 'https://facebook.com'
    - channel: "WhatsApp"
      add_to_chat_bubble: true
      url: 'https://facebook.com'
    - channel: "Messenger"
      add_to_chat_bubble: true
      url: 'https://facebook.com'
branding:
  site_title: RECONECTA - Exposição de Imagens
  nav_logo_image:
  footer_logo_image:
  preview_image: /assets/images/site-preview.png
navigation:
  menus:
    - name: About
      url: /about
      is_dropdown: false
      style_as_button: false
      submenus:
        - name:
          url:
    - name: Dropdown
      url: '#'
      is_dropdown: true
      style_as_button: false
      submenus:
        - name: Item 1
          url: /
        - name: Item 2
          url: /
        - name: Item 3
          url: /
    - name: More
      url: '#'
      is_dropdown: true
      style_as_button: false
      submenus:
        - name: Item 1
          url: /
        - name: Item 2
          url: /
        - name: Item 3
          url: /
seo:
  site_description_text:
  keywords:
configuration:
  head_code_block: >-
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Red+Rose:wght@400;500;600;700&family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300&display=swap" rel="stylesheet">
  body_code_block:
  custom_css_code_block:   